-- EH-SYSTEM — Seed data
--
-- Intentionally empty. Operational defaults live in the migrations themselves:
--   - AI behavior rows (prompts, editable live in /ai-control) are seeded by
--     migrations/0005_ai_behaviors.sql and pruned by 0010/0012.
--   - There is no fake business data by design: empty tables render real
--     "no data yet" states in the UI.
--
-- The previous version of this file inserted into ai_settings, a table dropped
-- by migrations/0012_production_cleanup.sql, so it failed on any database that
-- had all migrations applied.
select 1;
