/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AdminRole = "admin";

export type AvailabilityAssumption = "assume_available" | "confirmed_available" | "unavailable";

export type CampaignAssetKind = "ai_edited_image" | "ai_generated_image" | "final_post_image" | "original_product_image" | "uploaded_image";

export type CampaignStatus = "archived" | "draft" | "failed" | "paused" | "published" | "publishing" | "scheduled";

export type CampaignType = "category_sale" | "clearance" | "flash_sale" | "multi_product_carousel" | "seasonal" | "single_product_discount";

export type Channel = "facebook_comment" | "instagram" | "manual" | "messenger";

export type ConversationStatus = "ai_handling" | "blocked" | "cancelled" | "completed" | "delivery_requested" | "human_active" | "issue_refund_exchange" | "needs_human" | "new" | "order_confirmed" | "order_draft" | "pickup_requested" | "resolved" | "spam" | "waiting_for_customer" | "waiting_for_customer_info" | "waiting_for_order_confirmation";

export type FbPostStatus = "draft" | "failed" | "published" | "publishing" | "scheduled";

export type FbPostType = "carousel" | "image" | "text";

export type FulfillmentMethod = "delivery" | "pickup" | "undecided";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImageMatchOutcome = "corrected" | "exact" | "multiple" | "none";

export type ImportRunStatus = "completed" | "completed_with_errors" | "failed" | "running";

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type IntegrationKind = "cloudflare" | "gemini" | "meta" | "supabase";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MessageDirection = "inbound" | "outbound";

export type MessageSenderType = "ai" | "customer" | "human" | "system";

export type Numeric = ColumnType<number, number | string, number | string>;

export type OrderStatus = "cancelled" | "completed" | "issue_refund_exchange" | "waiting_for_customer_info" | "waiting_for_order_confirmation";

export type ProductStatus = "active" | "archived" | "draft" | "out_of_stock";

export type Timestamp = ColumnType<string, Date | string, Date | string>;

export interface ActivityLogs {
  action: string;
  actor_id: string | null;
  actor_type: Generated<string>;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  meta: Generated<Json>;
  summary: string | null;
}

export interface AdminAccounts {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  display_name: string | null;
  full_access: Generated<boolean>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  password_hash: string;
  preferred_locale: Generated<string>;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface AdminAuditLog {
  action: string;
  admin_id: string | null;
  admin_username: string | null;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<Int8>;
}

export interface AdminSessions {
  admin_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
}

export interface AdminUsers {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string | null;
  id: string;
  is_active: Generated<boolean>;
  last_seen_at: Timestamp | null;
  preferred_locale: Generated<string>;
  role: Generated<AdminRole>;
  updated_at: Generated<Timestamp>;
}

export interface AiBehaviors {
  behavior_key: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  memory: string | null;
  prompt: string | null;
  rules: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AiBehaviorVersions {
  behavior_key: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<Int8>;
  memory: string | null;
  note: string | null;
  prompt: string | null;
  rules: string | null;
  saved_by: string | null;
  title: string | null;
}

export interface AiTaskPrompts {
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  prompt: string;
  task_key: string;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AiTaskPromptVersions {
  created_at: Generated<Timestamp>;
  enabled: boolean;
  id: Generated<Int8>;
  note: string | null;
  prompt: string;
  saved_by: string | null;
  task_key: string;
  title: string;
}

export interface AiEvents {
  confidence: Numeric | null;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  detected_intent: string | null;
  error: string | null;
  id: Generated<string>;
  kind: string;
  latency_ms: number | null;
  model: string | null;
  output_summary: string | null;
  prompt_summary: string | null;
  related_id: string | null;
  success: Generated<boolean>;
  task: string | null;
  token_input: number | null;
  token_output: number | null;
  trace_id: string | null;
}

export interface AnalyticsDaily {
  computed_at: Generated<Timestamp>;
  day: Timestamp;
  detail: Generated<Json>;
  metric: string;
  value: Generated<Numeric>;
}

export interface BusinessFacts {
  key: string;
  label_ar: string | null;
  label_en: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface CampaignAssets {
  actual_model: string | null;
  approved: Generated<boolean>;
  campaign_id: string;
  caption: string | null;
  created_at: Generated<Timestamp>;
  fallback_used: Generated<boolean>;
  id: Generated<string>;
  kind: CampaignAssetKind;
  overlay_text_status: string | null;
  position: Generated<number>;
  product_fidelity_status: string | null;
  product_id: string | null;
  prompt_trace_id: string | null;
  public_url: string | null;
  requested_model: string | null;
  requested_overlay_text: string | null;
  source_asset_id: string | null;
  source_prompt: string | null;
  storage_path: string | null;
  verification: Generated<Json>;
}

export interface CampaignProducts {
  campaign_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  override_price: Numeric | null;
  position: Generated<number>;
  product_id: string;
}

export interface Campaigns {
  aspect_ratio: Generated<string>;
  auto_publish: Generated<boolean>;
  caption_prompt: string | null;
  caption_tone: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  design_prompt: string | null;
  discount_percent: Numeric | null;
  ends_at: Timestamp | null;
  generated_caption: string | null;
  id: Generated<string>;
  image_text: string | null;
  name: string;
  objective: string | null;
  priority: Generated<number>;
  publish_mode: Generated<string>;
  scheduled_for: Timestamp | null;
  starts_at: Timestamp | null;
  status: Generated<CampaignStatus>;
  target_channel: Generated<string>;
  type: Generated<CampaignType>;
  updated_at: Generated<Timestamp>;
}

export interface CatalogMatchSuggestions {
  confidence: string | null;
  created_at: Generated<Timestamp>;
  csv_product_id: string;
  evidence: Generated<Json>;
  id: Generated<string>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  score: Numeric | null;
  scraper_product_id: string | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ContentAssets {
  aspect_ratio: string | null;
  asset_role: Generated<string>;
  config_revision: number | null;
  content_item_id: string;
  created_at: Generated<Timestamp>;
  generation_run_id: string | null;
  height: number | null;
  id: Generated<string>;
  kind: string;
  overlay: Generated<Json>;
  position: Generated<number>;
  product_id: string | null;
  public_url: string | null;
  selected_for_publish: Generated<boolean>;
  source_model: string | null;
  storage_path: string | null;
  width: number | null;
  verification: Generated<Json>;
}

export interface ContentGenerationRuns {
  attempt_count: Generated<number>;
  config_fingerprint: string;
  config_revision: number;
  content_item_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  prompt_trace_id: string | null;
  quality_status: Generated<string>;
  requested_model: string | null;
  source_model: string | null;
  stage: Generated<string>;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  verification: Generated<Json>;
  warnings: Generated<Json>;
}

export interface ContentComments {
  author_external_id: string | null;
  author_name: string | null;
  body: string | null;
  commented_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  decision: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  parent_comment_id: string | null;
  provider_comment_id: string;
  publication_id: string;
  reply_error: string | null;
  reply_provider_id: string | null;
  reply_status: string | null;
  reply_text: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ContentItems {
  approved_at: Timestamp | null;
  approved_by: string | null;
  aspect_ratio: Generated<string>;
  caption: string | null;
  comment_automation: Generated<boolean>;
  config_revision: Generated<number>;
  content_type: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  creative_treatment: Generated<string>;
  id: Generated<string>;
  image_text: string | null;
  image_text_approved: Generated<boolean>;
  image_text_mode: Generated<string>;
  last_error: string | null;
  legacy_campaign_id: string | null;
  multi_product_layout: Generated<string>;
  output_mode: Generated<string>;
  platforms: Generated<string[]>;
  promotion_ends_at: Timestamp | null;
  purpose: Generated<string>;
  scheduled_for: Timestamp | null;
  selected_generation_run_id: string | null;
  status: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface BrandKit {
  accent_color: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  logo_public_url: string | null;
  logo_storage_path: string | null;
  primary_color: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  wordmark: Generated<string>;
}

export interface ContentProducts {
  content_item_id: string;
  id: Generated<string>;
  new_price: Numeric | null;
  position: Generated<number>;
  product_id: string;
  show_price: Generated<boolean>;
}

export interface ContentPublications {
  attempts: Generated<number>;
  content_item_id: string;
  created_at: Generated<Timestamp>;
  format: string;
  id: Generated<string>;
  idempotency_key: string;
  last_error: string | null;
  max_attempts: Generated<number>;
  next_attempt_at: Generated<Timestamp>;
  permalink_url: string | null;
  platform: string;
  provider_children: Generated<Json>;
  provider_post_id: string | null;
  published_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ConversationAttachments {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  id: Generated<string>;
  image_url: string | null;
  metadata: Generated<Json>;
  product_id: string | null;
  type: string;
}

export interface ConversationLabels {
  color: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  label: string;
}

export interface Conversations {
  ai_enabled: Generated<boolean>;
  assigned_admin_id: string | null;
  channel: Generated<Channel>;
  context_summary: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  customer_language: string | null;
  detected_intent: string | null;
  handoff_sent_at: Timestamp | null;
  human_attention: Generated<boolean>;
  human_attention_at: Timestamp | null;
  human_attention_reason: string | null;
  id: Generated<string>;
  is_spam: Generated<boolean>;
  last_customer_message_at: Timestamp | null;
  last_human_reply_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  next_turn_at: Timestamp | null;
  status: Generated<ConversationStatus>;
  takeover_admin_id: string | null;
  unread_count: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerMemory {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: Generated<string>;
  known_address: string | null;
  known_facts: Generated<string[]>;
  known_name: string | null;
  known_phone: string | null;
  last_conversation_at: Timestamp | null;
  preferences: Generated<Json>;
  recent_products: Generated<Json>;
  summary: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Customers {
  address: string | null;
  channel: Generated<Channel>;
  city: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  external_id: string | null;
  first_name: string | null;
  id: Generated<string>;
  is_blocked: Generated<boolean>;
  last_name: string | null;
  locale_guess: string | null;
  notes: string | null;
  phone: string | null;
  profile_pic_url: string | null;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface FacebookPosts {
  asset_ids: Generated<string[]>;
  campaign_id: string | null;
  caption: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  error: string | null;
  fb_post_id: string | null;
  id: Generated<string>;
  permalink_url: string | null;
  published_at: Timestamp | null;
  scheduled_for: Timestamp | null;
  status: Generated<FbPostStatus>;
  type: Generated<FbPostType>;
  updated_at: Generated<Timestamp>;
}

export interface ImageMatchCorrections {
  ai_suggested_product_ids: Generated<string[]>;
  ai_top_score: Numeric | null;
  conversation_id: string | null;
  corrected_by: string | null;
  corrected_product_id: string | null;
  created_at: Generated<Timestamp>;
  customer_image_hash: string | null;
  customer_image_path: string | null;
  customer_image_url: string | null;
  id: Generated<string>;
  message_id: string | null;
  notes: string | null;
  outcome: Generated<ImageMatchOutcome>;
}

export interface InboundEvents {
  attempts: Generated<number>;
  id: Generated<string>;
  last_error: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  provider: Generated<string>;
  provider_event_key: string | null;
  received_at: Generated<Timestamp>;
  status: Generated<string>;
  topic: string;
}

export interface IntegrationLogs {
  created_at: Generated<Timestamp>;
  direction: Generated<string>;
  endpoint: string | null;
  error: string | null;
  id: Generated<string>;
  integration: IntegrationKind;
  ok: Generated<boolean>;
  request: Json | null;
  response: Json | null;
  status_code: number | null;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  job_type: string;
  last_error: string | null;
  lease_expires_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  priority: Generated<number>;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LoginAttempts {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  ip: string | null;
  ok: Generated<boolean>;
  username: string | null;
}

export interface Messages {
  ai_meta: Generated<Json>;
  attachments: Generated<Json>;
  body: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  delivery_status: string | null;
  direction: MessageDirection;
  external_id: string | null;
  id: Generated<string>;
  is_internal_suggestion: Generated<boolean>;
  sender_admin_id: string | null;
  sender_type: MessageSenderType;
}

export interface OrderItemsArchive {
  base_price_snapshot: Numeric | null;
  campaign_id: string | null;
  created_at: Timestamp | null;
  id: string | null;
  line_total: Numeric | null;
  name_snapshot: string | null;
  order_id: string | null;
  product_code: string | null;
  product_id: string | null;
  quantity: number | null;
  unit_price: Numeric | null;
  variant_id: string | null;
}

export interface OrdersArchive {
  address: string | null;
  city: string | null;
  conversation_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  currency: string | null;
  customer_id: string | null;
  customer_name: string | null;
  delivery_notes: string | null;
  discount_total: Numeric | null;
  fulfillment: FulfillmentMethod | null;
  id: string | null;
  issue_notes: string | null;
  order_number: Int8 | null;
  phone: string | null;
  status: OrderStatus | null;
  subtotal: Numeric | null;
  total: Numeric | null;
  updated_at: Timestamp | null;
}

export interface OutboxMessages {
  attempts: Generated<number>;
  body: string | null;
  channel: string;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  image_url: string | null;
  kind: string;
  last_error: string | null;
  max_attempts: Generated<number>;
  message_id: string | null;
  next_attempt_at: Generated<Timestamp>;
  product_id: string | null;
  provider_message_id: string | null;
  recipient_id: string;
  sender_type: Generated<string>;
  sent_at: Timestamp | null;
  status: Generated<string>;
}

export interface ProductActivePricing {
  active_campaign_id: string | null;
  active_price: Numeric | null;
  base_price: Numeric | null;
  campaign_price: Numeric | null;
  product_id: string | null;
}

export interface ProductFamilies {
  created_at: Generated<Timestamp>;
  family_key: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  name: string;
  name_ar: string | null;
  notes: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ProductFieldChanges {
  changed_by: string | null;
  created_at: Generated<Timestamp>;
  field: string;
  id: Generated<Int8>;
  import_run_id: string | null;
  new_value: string | null;
  old_value: string | null;
  product_id: string;
  source: Generated<string>;
}

export interface ProductFingerprints {
  correction_id: string | null;
  created_at: Generated<Timestamp>;
  hash_hex: string;
  id: Generated<string>;
  product_id: string;
  source: Generated<string>;
}

export interface ProductImages {
  created_at: Generated<Timestamp>;
  embedding: Json | null;
  height: number | null;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  local_path: string | null;
  perceptual_hash: string | null;
  position: Generated<number>;
  product_id: string;
  public_url: string | null;
  storage_path: string | null;
  width: number | null;
}

export interface ProductImportRuns {
  created_count: Generated<number>;
  error_count: Generated<number>;
  errors: Generated<Json>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  skipped_count: Generated<number>;
  source: Generated<string>;
  source_file: string | null;
  started_at: Generated<Timestamp>;
  started_by: string | null;
  status: Generated<ImportRunStatus>;
  total_records: Generated<number>;
  updated_count: Generated<number>;
}

export interface ProductPriceHistory {
  changed_by: string | null;
  content_item_id: string | null;
  effective_at: Generated<Timestamp>;
  id: Generated<Int8>;
  import_run_id: string | null;
  new_price: Numeric | null;
  note: string | null;
  old_price: Numeric | null;
  product_id: string;
  source: string;
}

export interface ProductRelations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  locked: Generated<boolean>;
  product_id: string;
  related_product_id: string;
  relation_type: string;
  source: Generated<string>;
}

export interface Products {
  active_campaign_id: string | null;
  active_price: Numeric | null;
  /**
   * Map of field-name → true for fields an admin has edited. Sync/match/AI writers must not overwrite locked fields.
   */
  admin_locked_fields: Generated<Json>;
  arabic_keywords: Generated<string[]>;
  arabic_name: string | null;
  availability: Generated<AvailabilityAssumption>;
  barcode: string | null;
  base_price: Numeric | null;
  campaign_price: Numeric | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  english_name: string | null;
  family_id: string | null;
  family_locked: Generated<boolean>;
  id: Generated<string>;
  import_run_id: string | null;
  libyan_display_name: string | null;
  primary_image_id: string | null;
  product_code: string;
  raw: Generated<Json>;
  search_keywords: Generated<string[]>;
  search_tsv: string | null;
  source: Generated<string>;
  source_name: string | null;
  status: Generated<ProductStatus>;
  subcategory: string | null;
  text_embedding: Json | null;
  updated_at: Generated<Timestamp>;
  variant_attributes: Generated<Json>;
  variant_label: string | null;
  website_url: string | null;
}

export interface Promotions {
  content_item_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_at: Timestamp | null;
  id: Generated<string>;
  previous_price: Numeric;
  product_id: string;
  promo_price: Numeric;
  starts_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ProviderReadiness {
  check_key: string;
  checked_at: Generated<Timestamp>;
  detail: Generated<Json>;
  ok: boolean;
  summary: string | null;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  backfilled: Generated<boolean>;
  checksum: string | null;
  version: string;
}

export interface DB {
  activity_logs: ActivityLogs;
  admin_accounts: AdminAccounts;
  admin_audit_log: AdminAuditLog;
  admin_sessions: AdminSessions;
  admin_users: AdminUsers;
  ai_behavior_versions: AiBehaviorVersions;
  ai_task_prompts: AiTaskPrompts;
  ai_task_prompt_versions: AiTaskPromptVersions;
  ai_behaviors: AiBehaviors;
  ai_events: AiEvents;
  analytics_daily: AnalyticsDaily;
  brand_kit: BrandKit;
  business_facts: BusinessFacts;
  campaign_assets: CampaignAssets;
  campaign_products: CampaignProducts;
  campaigns: Campaigns;
  catalog_match_suggestions: CatalogMatchSuggestions;
  content_assets: ContentAssets;
  content_generation_runs: ContentGenerationRuns;
  content_comments: ContentComments;
  content_items: ContentItems;
  content_products: ContentProducts;
  content_publications: ContentPublications;
  conversation_attachments: ConversationAttachments;
  conversation_labels: ConversationLabels;
  conversations: Conversations;
  customer_memory: CustomerMemory;
  customers: Customers;
  facebook_posts: FacebookPosts;
  image_match_corrections: ImageMatchCorrections;
  inbound_events: InboundEvents;
  integration_logs: IntegrationLogs;
  jobs: Jobs;
  login_attempts: LoginAttempts;
  messages: Messages;
  order_items_archive: OrderItemsArchive;
  orders_archive: OrdersArchive;
  outbox_messages: OutboxMessages;
  product_active_pricing: ProductActivePricing;
  product_families: ProductFamilies;
  product_field_changes: ProductFieldChanges;
  product_fingerprints: ProductFingerprints;
  product_images: ProductImages;
  product_import_runs: ProductImportRuns;
  product_price_history: ProductPriceHistory;
  product_relations: ProductRelations;
  products: Products;
  promotions: Promotions;
  provider_readiness: ProviderReadiness;
  schema_migrations: SchemaMigrations;
}
