/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AdminRole = "admin";

export type AvailabilityAssumption = "assume_available" | "confirmed_available" | "unavailable";

export type CampaignAssetKind = "ai_edited_image" | "ai_generated_image" | "final_post_image" | "original_product_image" | "uploaded_image";

export type CampaignStatus = "archived" | "draft" | "failed" | "paused" | "published" | "publishing" | "scheduled";

export type CampaignType = "category_sale" | "clearance" | "flash_sale" | "multi_product_carousel" | "seasonal" | "single_product_discount";

export type Channel = "facebook_comment" | "instagram" | "manual" | "messenger";

export type ConversationStatus = "ai_handling" | "blocked" | "cancelled" | "completed" | "delivery_requested" | "human_active" | "issue_refund_exchange" | "needs_human" | "new" | "order_confirmed" | "order_draft" | "pickup_requested" | "resolved" | "spam" | "waiting_for_customer" | "waiting_for_customer_info" | "waiting_for_order_confirmation";

export type FbPostStatus = "draft" | "failed" | "published" | "publishing" | "scheduled";

export type FbPostType = "carousel" | "image" | "text";

export type FulfillmentMethod = "delivery" | "pickup" | "undecided";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImageMatchOutcome = "corrected" | "exact" | "multiple" | "none";

export type ImportRunStatus = "completed" | "completed_with_errors" | "failed" | "running";

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type IntegrationKind = "cloudflare" | "gemini" | "meta" | "supabase";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MessageDirection = "inbound" | "outbound";

export type MessageSenderType = "ai" | "customer" | "human" | "system";

export type Numeric = ColumnType<number, number | string, number | string>;

export type OrderStatus = "cancelled" | "completed" | "issue_refund_exchange" | "waiting_for_customer_info" | "waiting_for_order_confirmation";

export type ProductStatus = "active" | "archived" | "draft" | "out_of_stock";

export type Timestamp = ColumnType<string, Date | string, Date | string>;

export interface ActivityLogs {
  action: string;
  actor_id: string | null;
  actor_type: Generated<string>;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  meta: Generated<Json>;
  summary: string | null;
}

export interface AdminUsers {
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string | null;
  id: string;
  is_active: Generated<boolean>;
  last_seen_at: Timestamp | null;
  preferred_locale: Generated<string>;
  role: Generated<AdminRole>;
  updated_at: Generated<Timestamp>;
}

export interface AiBehaviors {
  behavior_key: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  memory: string | null;
  prompt: string | null;
  rules: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AiEvents {
  confidence: Numeric | null;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  detected_intent: string | null;
  error: string | null;
  id: Generated<string>;
  kind: string;
  latency_ms: number | null;
  model: string | null;
  output_summary: string | null;
  prompt_summary: string | null;
  related_id: string | null;
  success: Generated<boolean>;
  token_input: number | null;
  token_output: number | null;
}

export interface CampaignAssets {
  approved: Generated<boolean>;
  campaign_id: string;
  caption: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: CampaignAssetKind;
  position: Generated<number>;
  product_id: string | null;
  public_url: string | null;
  source_asset_id: string | null;
  source_prompt: string | null;
  storage_path: string | null;
}

export interface CampaignProducts {
  campaign_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  override_price: Numeric | null;
  position: Generated<number>;
  product_id: string;
}

export interface Campaigns {
  auto_publish: Generated<boolean>;
  caption_prompt: string | null;
  caption_tone: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  design_prompt: string | null;
  discount_percent: Numeric | null;
  ends_at: Timestamp | null;
  generated_caption: string | null;
  id: Generated<string>;
  name: string;
  priority: Generated<number>;
  publish_mode: Generated<string>;
  scheduled_for: Timestamp | null;
  starts_at: Timestamp | null;
  status: Generated<CampaignStatus>;
  type: Generated<CampaignType>;
  updated_at: Generated<Timestamp>;
}

export interface CatalogMatchSuggestions {
  confidence: string | null;
  created_at: Generated<Timestamp>;
  csv_product_id: string;
  evidence: Generated<Json>;
  id: Generated<string>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  score: Numeric | null;
  scraper_product_id: string | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ConversationAttachments {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  id: Generated<string>;
  image_url: string | null;
  metadata: Generated<Json>;
  product_id: string | null;
  type: string;
}

export interface ConversationLabels {
  color: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  label: string;
}

export interface Conversations {
  ai_enabled: Generated<boolean>;
  assigned_admin_id: string | null;
  channel: Generated<Channel>;
  context_summary: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  customer_language: string | null;
  detected_intent: string | null;
  id: Generated<string>;
  is_spam: Generated<boolean>;
  last_customer_message_at: Timestamp | null;
  last_human_reply_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  next_turn_at: Timestamp | null;
  status: Generated<ConversationStatus>;
  unread_count: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerMemory {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: Generated<string>;
  known_address: string | null;
  known_facts: Generated<string[]>;
  known_name: string | null;
  known_phone: string | null;
  last_conversation_at: Timestamp | null;
  preferences: Generated<Json>;
  recent_products: Generated<Json>;
  summary: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Customers {
  address: string | null;
  channel: Generated<Channel>;
  city: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  external_id: string | null;
  first_name: string | null;
  id: Generated<string>;
  is_blocked: Generated<boolean>;
  last_name: string | null;
  locale_guess: string | null;
  notes: string | null;
  phone: string | null;
  profile_pic_url: string | null;
  tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface FacebookPosts {
  asset_ids: Generated<string[]>;
  campaign_id: string | null;
  caption: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  error: string | null;
  fb_post_id: string | null;
  id: Generated<string>;
  permalink_url: string | null;
  published_at: Timestamp | null;
  scheduled_for: Timestamp | null;
  status: Generated<FbPostStatus>;
  type: Generated<FbPostType>;
  updated_at: Generated<Timestamp>;
}

export interface ImageMatchCorrections {
  ai_suggested_product_ids: Generated<string[]>;
  ai_top_score: Numeric | null;
  conversation_id: string | null;
  corrected_by: string | null;
  corrected_product_id: string | null;
  created_at: Generated<Timestamp>;
  customer_image_hash: string | null;
  customer_image_path: string | null;
  customer_image_url: string | null;
  id: Generated<string>;
  message_id: string | null;
  notes: string | null;
  outcome: Generated<ImageMatchOutcome>;
}

export interface IntegrationLogs {
  created_at: Generated<Timestamp>;
  direction: Generated<string>;
  endpoint: string | null;
  error: string | null;
  id: Generated<string>;
  integration: IntegrationKind;
  ok: Generated<boolean>;
  request: Json | null;
  response: Json | null;
  status_code: number | null;
}

export interface Messages {
  ai_meta: Generated<Json>;
  attachments: Generated<Json>;
  body: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  direction: MessageDirection;
  external_id: string | null;
  id: Generated<string>;
  is_internal_suggestion: Generated<boolean>;
  sender_admin_id: string | null;
  sender_type: MessageSenderType;
}

export interface OrderItemsArchive {
  base_price_snapshot: Numeric | null;
  campaign_id: string | null;
  created_at: Timestamp | null;
  id: string | null;
  line_total: Numeric | null;
  name_snapshot: string | null;
  order_id: string | null;
  product_code: string | null;
  product_id: string | null;
  quantity: number | null;
  unit_price: Numeric | null;
  variant_id: string | null;
}

export interface OrdersArchive {
  address: string | null;
  city: string | null;
  conversation_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  currency: string | null;
  customer_id: string | null;
  customer_name: string | null;
  delivery_notes: string | null;
  discount_total: Numeric | null;
  fulfillment: FulfillmentMethod | null;
  id: string | null;
  issue_notes: string | null;
  order_number: Int8 | null;
  phone: string | null;
  status: OrderStatus | null;
  subtotal: Numeric | null;
  total: Numeric | null;
  updated_at: Timestamp | null;
}

export interface ProductActivePricing {
  active_campaign_id: string | null;
  active_price: Numeric | null;
  base_price: Numeric | null;
  campaign_price: Numeric | null;
  product_id: string | null;
}

export interface ProductFingerprints {
  correction_id: string | null;
  created_at: Generated<Timestamp>;
  hash_hex: string;
  id: Generated<string>;
  product_id: string;
  source: Generated<string>;
}

export interface ProductImages {
  created_at: Generated<Timestamp>;
  embedding: Json | null;
  height: number | null;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  local_path: string | null;
  perceptual_hash: string | null;
  position: Generated<number>;
  product_id: string;
  public_url: string | null;
  storage_path: string | null;
  width: number | null;
}

export interface ProductImportRuns {
  created_count: Generated<number>;
  error_count: Generated<number>;
  errors: Generated<Json>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  skipped_count: Generated<number>;
  source: Generated<string>;
  source_file: string | null;
  started_at: Generated<Timestamp>;
  started_by: string | null;
  status: Generated<ImportRunStatus>;
  total_records: Generated<number>;
  updated_count: Generated<number>;
}

export interface Products {
  active_campaign_id: string | null;
  active_price: Numeric | null;
  /**
   * Map of field-name → true for fields an admin has edited. Sync/match/AI writers must not overwrite locked fields.
   */
  admin_locked_fields: Generated<Json>;
  arabic_keywords: Generated<string[]>;
  arabic_name: string | null;
  availability: Generated<AvailabilityAssumption>;
  barcode: string | null;
  base_price: Numeric | null;
  campaign_price: Numeric | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  english_name: string | null;
  id: Generated<string>;
  import_run_id: string | null;
  libyan_display_name: string | null;
  primary_image_id: string | null;
  product_code: string;
  raw: Generated<Json>;
  search_keywords: Generated<string[]>;
  source: Generated<string>;
  source_name: string | null;
  status: Generated<ProductStatus>;
  subcategory: string | null;
  text_embedding: Json | null;
  updated_at: Generated<Timestamp>;
  website_url: string | null;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  version: string;
}

export interface DB {
  activity_logs: ActivityLogs;
  admin_users: AdminUsers;
  ai_behaviors: AiBehaviors;
  ai_events: AiEvents;
  campaign_assets: CampaignAssets;
  campaign_products: CampaignProducts;
  campaigns: Campaigns;
  catalog_match_suggestions: CatalogMatchSuggestions;
  conversation_attachments: ConversationAttachments;
  conversation_labels: ConversationLabels;
  conversations: Conversations;
  customer_memory: CustomerMemory;
  customers: Customers;
  facebook_posts: FacebookPosts;
  image_match_corrections: ImageMatchCorrections;
  integration_logs: IntegrationLogs;
  messages: Messages;
  order_items_archive: OrderItemsArchive;
  orders_archive: OrdersArchive;
  product_active_pricing: ProductActivePricing;
  product_fingerprints: ProductFingerprints;
  product_images: ProductImages;
  product_import_runs: ProductImportRuns;
  products: Products;
  schema_migrations: SchemaMigrations;
}
